### ISSUE TITLE
Directory structure for mails is not available

### ISSUE THREAD

**Issue by jlistemann-ish** [intershop/iom-project-archetype#10]
The structure for mails is not as documented in
https://intershop.atlassian.net/wiki/spaces/ENFDEVDOC/pages/47890466140/Guide+-+IOM+Standard+Project+Structure#Guide-Teh IOMStandardProjectStructure-6MailTemplates
The mail image folder is missing.

**Comment by Philipp-Borchert-ISH** [comment]
closing / obsolete as discussed
